// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type NavigationDocumentDataSlicesSlice = NavInfoSectionSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Navigation Links field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Navigation LInk
   * - **API ID Path**: navigation.navigation_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigation_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Left Footer Text field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Text content for left of navigation footer
   * - **API ID Path**: navigation.left_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  left_text: prismic.KeyTextField;

  /**
   * Right Footer Text field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Text content for right of navigation footer
   * - **API ID Path**: navigation.right_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  right_text: prismic.KeyTextField;

  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>; /**
   * Meta Title field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: navigation.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: navigation.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Page Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;

  /**
   * Page Number field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Number
   * - **API ID Path**: page.page_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_number: prismic.KeyTextField;

  /**
   * Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Description
   * - **API ID Path**: page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Background Color field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: Background Color
   * - **API ID Path**: page.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;

  /**
   * Font Color field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: Font Color
   * - **API ID Path**: page.font_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  font_color: prismic.ColorField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Project → Gallery*
 */
export interface ProjectDocumentDataGalleryItem {
  /**
   * Image field in *Project → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.gallery[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Project Title
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Number field in *Project*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Project Number
   * - **API ID Path**: project.number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  number: prismic.NumberField;

  /**
   * Year field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Project Year
   * - **API ID Path**: project.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  year: prismic.KeyTextField;

  /**
   * Background Color field in *Project*
   *
   * - **Field Type**: Color
   * - **Placeholder**: Background Color
   * - **API ID Path**: project.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;

  /**
   * Thumbnail field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Gallery field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery: prismic.GroupField<Simplify<ProjectDocumentDataGalleryItem>>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

export type AllDocumentTypes =
  | NavigationDocument
  | PageDocument
  | ProjectDocument;

/**
 * Item in *NavInfoSection → Default → Primary → Section Items*
 */
export interface NavInfoSectionSliceDefaultPrimarySectionItemsItem {
  /**
   * Section Item field in *NavInfoSection → Default → Primary → Section Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section Item
   * - **API ID Path**: nav_info_section.default.primary.section_items[].section_item
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_item: prismic.KeyTextField;
}

/**
 * Primary content in *NavInfoSection → Default → Primary*
 */
export interface NavInfoSectionSliceDefaultPrimary {
  /**
   * Title field in *NavInfoSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section Title
   * - **API ID Path**: nav_info_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Section Number field in *NavInfoSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section Number
   * - **API ID Path**: nav_info_section.default.primary.section_number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_number: prismic.KeyTextField;

  /**
   * Section Items field in *NavInfoSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_info_section.default.primary.section_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  section_items: prismic.GroupField<
    Simplify<NavInfoSectionSliceDefaultPrimarySectionItemsItem>
  >;
}

/**
 * Default variation for NavInfoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavInfoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavInfoSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavInfoSection*
 */
type NavInfoSectionSliceVariation = NavInfoSectionSliceDefault;

/**
 * NavInfoSection Shared Slice
 *
 * - **API ID**: `nav_info_section`
 * - **Description**: NavInfoSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavInfoSectionSlice = prismic.SharedSlice<
  "nav_info_section",
  NavInfoSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataGalleryItem,
      AllDocumentTypes,
      NavInfoSectionSlice,
      NavInfoSectionSliceDefaultPrimarySectionItemsItem,
      NavInfoSectionSliceDefaultPrimary,
      NavInfoSectionSliceVariation,
      NavInfoSectionSliceDefault,
    };
  }
}
