// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  gallery: dynamic(() => import("./Gallery")),
  image: dynamic(() => import("./Image")),
  list: dynamic(() => import("./List")),
  text_block: dynamic(() => import("./TextBlock")),
};
